{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  agentToken: {{ required "A valid CloudXray K8s agent token is required" .Values.general.agentToken | b64enc | quote }}
{{- end }}
